from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Tuple

class RobotInterface(ABC):
    @abstractmethod
    def move_to(self, pose: Tuple[float, float, float]) -> dict: ...
    @abstractmethod
    def grasp(self, target: str) -> dict: ...
    @abstractmethod
    def lift(self, target: str, dz: float) -> dict: ...
    @abstractmethod
    def place(self, target: str, pose: Tuple[float, float, float], container: str | None = None) -> dict: ...
    @abstractmethod
    def release(self) -> dict: ...
